blank_issues_enabled: false
contact_links:
  - name: Request For Comments (RFC)
    about: You have an idea on how to improve our processes. Propose your idea so that the team can provide feedback.
    url: >
      https://github.com/nimblehq/compass/discussions/new?category=rfcs&body=
      ## Issue

      Describe the issue the team is currently facing. Provide as much content as possible.

      ## Solution

      Describe the solution you are prescribing for the issue

      ## Who Benefits?

      Describe who will be the beneficiaries e.g. everyone, specific chapters, clients...

      ## What's Next?

      Provide an actionable list of things that must happen in order to implement the solution:

      - [ ]
      - [ ]
      - [ ]

      Using a poll is encouraged to gather feedback on the RFA 👉 Use this tool: https://gh-polls.com/

  - name: Ask a question related to governance
    url: https://github.com/kedacore/governance/discussions/new
    about: Ask a question about the governance of KEDA
