blank_issues_enabled: false

contact_links:
  - name: Request For Comments (RFC)
    about: When having an idea on how to improve our processes. Propose the idea so that the team can provide feedback.
    # Set discussion template by using the template query parameters
    url: https://github.com/nimblehq/compass/discussions/new?category=rfcs&title=RFC:+&body=Refer+to+the+instruction+at+https%3A%2F%2Fnimblehq.co%2Fcompass%2Fintro%2Fchange-management

  - name: Ask a question
    about: When having a question about a pull request, issue, or problem, create a Q&A discussion to get help from the team.
    url: https://github.com/nimblehq/compass/discussions/new?category=q-a


