import ReactMarkdown from 'react-markdown';

import { gql, GraphQLClient } from 'graphql-request';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const API_URL = `https://api.github.com/graphql`;

  const graphQLClient = new GraphQLClient(API_URL, {
    headers: {
      Authorization: `Bearer ${process.env.API_KEY}`,
    },
  });
  const {
    repository: {
      issues: { nodes },
    },
  } = await graphQLClient.request(gql`
    query {
      repository(name: "articly", owner: "hoangmirs") {
        issues(first: 10) {
          nodes {
            author {
              login
            }
            id
            title
            body
            url
          }
          pageInfo {
            endCursor
            startCursor
          }
          totalCount
        }
      }
    }
  `);

  console.log(nodes);

  return {
    props: {
      issues: nodes as Issue[],
    },
  };
}

interface Author {
  login: string;
}

interface Issue {
  id: string;
  author: Author;
  title: string;
  body: string;
  url: string;
}

interface IndexProps {
  issues: Issue[];
}

const Home = ({ issues }: IndexProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div>
          {issues.map((issue) => (
            <div className={styles.card} key={issue.id}>
              <a href={issue.url}>
                <h2>{issue.title}</h2>
              </a>
              <div>
                <ReactMarkdown>{issue.body}</ReactMarkdown>
              </div>
            </div>
          ))}
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
